import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { useState } from "react";
import Navbar from "@/components/Navbar/Navbar";
import { AuthContext } from "@/contexts/AuthContext";
import { AuthProvider } from "@/contexts/AuthProvider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");

  console.log(cookieStore.getAll());

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />

          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
